apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ocs-cluster
  namespace: openshift-storage
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ovn-k8s-mp0",
      "mode": "bridge",
      "ipam": {
            "type": "whereabouts",
            "range": "192.168.0.0/24"
      }
  }'
