---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: ocs-storagecluster
spec:
  coreResources:
    limits:
      cpu: 999m
      memory: 4Gi
    requests:
      cpu: 999m
      memory: 4Gi
  dbResources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi
  storageDeviceSets:
  - name: ocs-deviceset
    count: 1
    replica: 3
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: null
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1Ti
    portable: true
